### ISSUE TITLE
Spicetify-cli: Some scripts are not recognised as cmdlet, scripts, ...

### ISSUE THREAD

**Issue by jacob-thanh** [zwxi/Scoop-Spotify#11]
When I first installed and later updated this bucket through scoop, I got this error message:
```yml
The term: init-spicetify-config-and-apply.ps1 is not recognized as a name of a cmdlet, function, script ...
```
Basically it's not in path, and failed the rest of the installation process.

It seems that all the scripts from this bucket's [`scripts folder`](https://github.com/zwxi/Scoop-Spotify/tree/main/scripts) are not copied into where `spicetify-cli` is installed. I did a manually fix by copying all scripts into where it's needed, but each update is troublesome. So I submit a new issue.
This error may happened because there is another [`bucket (main)`](https://github.com/ScoopInstaller/Main/) which also contains [`spicetify-cli`](https://github.com/zwxi/Scoop-Spotify/blob/main/bucket/spicetify-cli.json), and this line in [<code>your&nbsp;spicetify-cli</code>](https://github.com/zwxi/Scoop-Spotify/blob/8b77ae3d20f7270c421a79875be8241c8c01296c/bucket/spicetify-cli.json#L21):
```json
      "installer": {
        "script": [
            "...",
            "$null, $bucket = find_manifest($app)", <---
            "$bucketdir = Find-BucketDirectory($bucket)",
           "...", 
        ]
      } 
```
Without `find_manifest($app, $bucket)` specifying which bucket, it's set to default as main bucket, whose [script folder](https://github.com/ScoopInstaller/Main/tree/master/scripts) does not contains necessary scripts like `init-spicetify-config-and-apply.ps1`, `spicetify-apply.ps1`, ... and the [`following line`](https://github.com/zwxi/Scoop-Spotify/blob/8b77ae3d20f7270c421a79875be8241c8c01296c/bucket/spicetify-cli.json#L23)
```pwsh
    @(all the scripts) | ForEach-Object { Copy-Item "..." } ;
``` 
fail, never made it into `spicetify-cli` installation directory.
I suggest changing that line into 
```pwsh
    "$null, $bucket = find_manifest $app 'spotify'",
```
as 
```pwsh
     find_manifest($app, 'spotify'),
``` 
both will be passed as array into `$app` param.
I am submitting this issue to both the original repo and your fork (as the original still getting new commits and [Buckets | Scoop](https://scoop.netlify.app/buckets/) still linked to that repo).
I'm sorry for the verbosity, hope this help anyone who encounter the same problem as I did.

**Comment by rollingmoai** [comment]
https://github.com/TheRandomLabs/Scoop-Spotify/issues/66#issuecomment-1086774485

**Comment by o1x3** [comment]
Thank you for you input @jacob-thanh  but as @itsmeboy0  said, feel free to switch to the official repo. 

However I will definitley implement what you suggested. If you want, feel free to submit the change as a Pull Request so that it will be credited as your idea.

I didn't notice this issue since I was manually holding back from updating spotify and spicetify due to compatibality issues with 1.1.82 version of spotify

**Comment by o1x3** [comment]
a452d979c3ae51d10705d2c38d37d641d780e4f6
