### ISSUE TITLE
BlockTheSpot incomplete / outdated

### ISSUE THREAD

**Issue by Luckz** [zwxi/Scoop-Spotify#6]
This version of BlockTheSpot is missing the upgrade & ad area removal.
Just applying the two changes in upstream https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1 for that works well for me:
in \scoop\apps\spotify-latest\current\Apps\xpui\xpui.js:
regex-replace
`(\.ads\.leaderboard\.isEnabled)(}|\))`
with
`$1&&false$2`
and
`\.createElement\([^.,{]+,{onClick:[^.,]+,className:[^.]+\.[^.]+\.UpgradeButton}\),[^.(]+\(\)`
with nothing

(upstream extracts this from zip, edits it, and re-packs it into the xpui archive, but over here we just use an extracted xpui.js at runtime)

**Comment by Luckz** [comment]
(I should add that some people also like removing the `Upgrade to Premium` button in the user dropdown. Since it's literally just a link to https://www.spotify.com/premium/ I'm not sure if removing that too would be reducing functionality or improving the UI.)

**Comment by o1x3** [comment]
@Luckz I am a bit busy this week since I have exams till Sunday 😅. I'll surely work on this after I'm done with my exams.

But if you can post a PR patching [blockthespot.ps1](https://github.com/zwxi/Scoop-Spotify/blob/main/scripts/blockthespot.ps1) and [blockthespot.json ](https://github.com/zwxi/Scoop-Spotify/blob/main/bucket/blockthespot.json)to backup `xpui.js` then regex replace and restore the original `xpui.js` on uninstallation of `blockthespot` , I can merge it ASAP

**Comment by o1x3** [comment]
@Luckz 950e9a2e2d57da73caff6e587cf0f2018178e5e7 is a possible fix but it requires spicetfy to be installed

**Comment by Luckz** [comment]
Now, installing blockthespot runs the script and applies these changes, but spicetify-apply and the like undo them again. 
i.e. a fresh install `scoop install spotify-latest spicetify-cli blockthespot spicetify-themes` leaves you without them.
`scoop remove blockthespot`, `scoop install blockthespot` applies the changes and removes the parts in question.
`spicetify-apply` undoes the changes again.
running `blockthespot` (which I guess is what spicetify-apply does in effect) does not fix anything.

But I realised why that happens, and: https://github.com/zwxi/Scoop-Spotify/pull/8

The other issue is that since blockthespot.ps1 is only copied on install from the bucket to apps, it will not be updated. The best approach I suppose would be to increment the version on major .ps1 changes to force the install script to run again and rectify this.
The alternative approach of making the ps1 a symlink rather than a copy has more major downsides, namely that if a user chooses not to update this package, they'll might be running newer code automagically.

**Comment by Luckz** [comment]
> (I should add that some people also like removing the `Upgrade to Premium` button in the user dropdown. Since it's literally just a link to https://www.spotify.com/premium/ I'm not sure if removing that too would be reducing functionality or improving the UI.)

And while talking about that, there's an annoying new "3 months free premium" advert, which also appears in the client:
https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/commit/aa72cab7a7bf7a995658f109f38720747e02b4ef

**Comment by o1x3** [comment]
> The other issue is that since blockthespot.ps1 is only copied on install from the bucket to apps, it will not be updated. The best approach I suppose would be to increment the version on major .ps1 changes to force the install script to run again and rectify this. 

The problem is that blockthespot.json version is directly tied to the release versions from the blockthespot repo to download the latest chrome_elf package. So I guess the solution is to restructure the blockthespot package as a whole and include the downloading part in blockthespot.ps1 and skip the copying over step altogether.

**Comment by o1x3** [comment]
> > (I should add that some people also like removing the `Upgrade to Premium` button in the user dropdown. Since it's literally just a link to https://www.spotify.com/premium/ I'm not sure if removing that too would be reducing functionality or improving the UI.)
> 
> And while talking about that, there's an annoying new "3 months free premium" advert, which also appears in the client: [cvzi/Spotify-Genius-Lyrics-userscript@aa72cab](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/commit/aa72cab7a7bf7a995658f109f38720747e02b4ef)

The userscript just clicks the element when it pops up. If we must remove that we need to remove the element altogether.

**Comment by Luckz** [comment]
> > The other issue is that since blockthespot.ps1 is only copied on install from the bucket to apps, it will not be updated. The best approach I suppose would be to increment the version on major .ps1 changes to force the install script to run again and rectify this.
> 
> The problem is that blockthespot.json version is directly tied to the release versions from the blockthespot repo to download the latest chrome_elf package. So I guess the solution is to restructure the blockthespot package as a whole and include the downloading part in blockthespot.ps1 and skip the copying over step altogether.

Well, yes and no. Assuming that install scripts run every time there is a version change, one can simply increment the JSON version "in some way" (custom) when making substantial changes to the .ps1, so that an automatic upstream update would yet again lead to a higher version.
I didn't check how scoop string-compares to determine what version is higher [ok, now I googled for a second], or if merely having a newer / different JSON could do the trick - but in any case, it's sure possible to increment the version by hand.

From how I read https://github.com/ScoopInstaller/Scoop/blob/master/test/Scoop-Versions.Tests.ps1 , it should be fine to change it like `2021.10.29.44` -> `2021.10.29.44.1` or `2021.10.29.44+custom.0`. It'd be a bit weird but still fine to use `2021.10.29.45`, since a newer `2021.12.31.45` would win over it as well.

**Comment by o1x3** [comment]
> 

Yes that is a great idea. Any changes to blockthespot.ps1 can be accompanied with a minor increment to make it copy blockthespot.ps1 to apply the changes

I take it mrpond/BlockTheSpot@10ec23b8bfecf1a07b26721fda1e88257d3f2d4b doesn't make any substantial changes to the install script (just a rewrite of the same idea). I only have working knowledge of PS scripts and I forked an worked on this repo only out of necessity 😅

**Comment by o1x3** [comment]
You can PR the version change to blockthespot.json to so that it'll show it was your idea xD

**Comment by Luckz** [comment]
> You can PR the version change to blockthespot.json to so that it'll show it was your idea xD

What version style would you like for a custom increment? Doesn't have to be one of the ones I suggested of course.

> I take it [mrpond/BlockTheSpot@10ec23b](https://github.com/mrpond/BlockTheSpot/commit/10ec23b8bfecf1a07b26721fda1e88257d3f2d4b) doesn't make any substantial changes to the install script (just a rewrite of the same idea).

It looks like it "only" adds cross platform compat that we don't care for.

**Comment by o1x3** [comment]
> > You can PR the version change to blockthespot.json to so that it'll show it was your idea xD
> 
> What version style would you like for a custom increment? Doesn't have to be one of the ones I suggested of course.
> 
> > I take it [mrpond/BlockTheSpot@10ec23b](https://github.com/mrpond/BlockTheSpot/commit/10ec23b8bfecf1a07b26721fda1e88257d3f2d4b) doesn't make any substantial changes to the install script (just a rewrite of the same idea).
> 
> It looks like it "only" adds cross platform compat that we don't care for.

The PR is perfect. Thanks for the help

**Comment by o1x3** [comment]
@Luckz It seems like the github-actions for auto update fill undo the custom increment anyway @ 62805330bb844d02f213acd2465403102e9affca

**Comment by Luckz** [comment]
> @Luckz It seems like the github-actions for auto update fill undo the custom increment anyway @ [6280533](https://github.com/zwxi/Scoop-Spotify/commit/62805330bb844d02f213acd2465403102e9affca)

Either we could try a different form of increment, find out what version comparison github actions uses (I'm really not sure how Excavator works), or there's some general bug with auto updates at the moment, f.ex.:
https://github.com/Calinou/scoop-games/search?q=betterjoy&type=commits ("updated" to older & lower 2020 version suddenly)




Upon doing more research, it seems checkver.ps1 doesn't even care if the version listed on Github (or wherever else it checks) is higher or lower:
![image](https://user-images.githubusercontent.com/224748/147406985-00c43d6e-bd88-44c6-98c1-f50e214d6b7d.png)
https://github.com/ScoopInstaller/Scoop/blob/master/bin/checkver.ps1#L120

So I guess this would require using a different version checking choice than automagic-newest-Github.

**Comment by o1x3** [comment]
> > @Luckz It seems like the github-actions for auto update fill undo the custom increment anyway @ [6280533](https://github.com/zwxi/Scoop-Spotify/commit/62805330bb844d02f213acd2465403102e9affca)
> 
> Either we could try a different form of increment, find out what version comparison github actions uses (I'm really not sure how Excavator works), or there's some general bug with auto updates at the moment, f.ex.: https://github.com/Calinou/scoop-games/search?q=betterjoy&type=commits ("updated" to older & lower 2020 version suddenly)
> 
> Upon doing more research, it seems checkver.ps1 doesn't even care if the version listed on Github (or wherever else it checks) is higher or lower: ![image](https://user-images.githubusercontent.com/224748/147406985-00c43d6e-bd88-44c6-98c1-f50e214d6b7d.png) https://github.com/ScoopInstaller/Scoop/blob/master/bin/checkver.ps1#L120
> 
> So I guess this would require using a different version checking choice than automagic-newest-Github.

Well we can keep experimenting as long as no merge conflict comes up on the main branch and Excavator force pushes onto it and everyone's local repo gets messed up

**Comment by Luckz** [comment]
I asked in Scoop Installer issue 4506 (..avoiding a two way link here..) – it seems the accepted practice is to sabotage the checkver configuration until a new version is out :/

Maybe someone else will chime in there with a reasonable idea.

**Comment by o1x3** [comment]
> 4506

We can wait for someone to find some solution/make one ig

**Comment by rollingmoai** [comment]
Just a quick note as I have done in another issue, An [AdBlock extension](https://github.com/CharlieS1103/spicetify-extensions/tree/main/adblock) [already exists](https://github.com/Daksh777/SpotifyNoPremium) in Spicetify.

**Comment by o1x3** [comment]
@itsmeboy0 updated ddfa4692a90d879795baae1aafe3801fcf93c0be f36916ca461c1b8064c3b829a70abb71af71d240
